### PR TITLE
Fix escaped strings handling

### LINKED ISSUE #85: Reading strings with escaped stuff seems incorrect
For example here:
````julia
 s = "Foo \\\"bar"

tryparsenext(Quoted(String, quotechar='"', escapechar='\\'), s)
````
I would expect that to return a string with content:
````
Foo "bar
````
Instead I get
````
Foo \"bar
````

In general I'm confused how the strategy of essentially just returning a position and a length that indexes into the source string a la [this](https://github.com/JuliaComputing/TextParse.jl/blob/1646a4bf0945e9496c858eae455a14b9d82a44e6/src/field.jl#L359) can ever work properly in this situation. After all, if you read a string with an escape character, the parsed string should actually *not* include that escape character, so don't you necessarily need a different memory buffer for that?

@shashi am I missing something in my analysis?

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #85.

@shashi could you take a look whether you are ok with the general strategy here? It is not yet done, but it would be good to get some feedback before I continue with this one here.

I generally have changed how the case of `Vector{String}` is handled: in that case this PR is no longer using `StrRange` at all, but is allocating the `String` in the `tryparsenext` method itself. I didn't see a benefit of going through `StrRange`, and it cuts down on the places that need to handle the escaping stuff.

This does *not yet* work with `StringArray`. I'm not sure I'll have the time to implement this for `StringArray` as well, in particular given that I'm not using it at all. Maybe someone from the JuliaDB team could sort out that part? Or, alternatively, but clearly not ideal, we could also for now just fix the bug for the `Vector{String}` case and then later try to fix it for `StringArray` as well.

Oh, and it would be great if you could carefully look over my changes to the tests. I think they now reflect a world in which escape char is handled properly, but it would be good to have that double checked :)

### CODE REVIEW

File: src/field.jl [hunk 1]
```diff
@@ -358,14 +364,41 @@ function tryparsenext(s::StringToken{T}, str, i, len, opts) where {T}
...
+        end
+        return String(take!(buf))
+    else
+        return unsafe_string(pointer(str, i), j-i+1)
+    end
 end
 
-@inline function _substring(::Type{T}, str, i, j) where {T<:SubString}
+@inline function _substring(::Type{T}, str, i, j, escapecount, escapechar, quotechar, includequotes) where {T<:SubString}
+    escapecount > 0 && error("Not yet handled.")
```
Comment (davidanthoff) [inline src/field.jl]: In general it is actually not clear to me when method would ever be called...

File: src/field.jl [hunk 2]
```diff
@@ -375,11 +408,12 @@ fromtype(::Type{StrRange}) = StringToken(StrRange)
...
 
-@inline function _substring(::Type{StrRange}, str, i, j)
-    StrRange(i - 1, j - i + 1)
+@inline function _substring(::Type{StrRange}, str, i, j, escapecount, escapechar, quotechar, includequotes)
+    StrRange(i - 1, j - i + 1, escapecount)
 end
 
-@inline function _substring(::Type{<:WeakRefString}, str, i, j)
+@inline function _substring(::Type{<:WeakRefString}, str, i, j, escapecount, escapechar, quotechar, includequotes)
+    escapecount > 0 && error("Not yet handled.")
```
Comment (davidanthoff) [inline src/field.jl]: I think this is mostly called for detecting NA strings? Or somewhere else? I'd be tempted to leave the error message in here until we find a situation where this actually needs to handle escaping.

File: src/record.jl [hunk 3]
```diff
@@ -96,11 +96,13 @@ end
 end
 
 @inline function setcell!(col::Array{String,1}, i, val::StrRange, str)
+    val.escapecount>0 && error("Not yet implemented")
     col[i] = alloc_string(str, val)
     PARSE_SUCCESS
 end
```
Comment (davidanthoff) [inline src/record.jl]: I believe this whole method will now never be called anymore because `Vector{String}` should never use `StrRange` anymore. So we could probably just remove the whole method.

File: src/record.jl [hunk 4]
```diff
@@ -96,11 +96,13 @@ end
...
 
 @inline Base.@propagate_inbounds function setcell!(col::StringVector, i, val::StrRange, str)
+    val.escapecount>0 && error("Not yet implemented")
```
Comment (davidanthoff) [inline src/record.jl]: This is the place where the escaping would have to be handled for `StringArray`.

File: src/record.jl (hunk 3 above)
Comment (shashi) [reply src/record.jl]: Yes I think this is vestigial from before we started using StringArrays

Comment (davidanthoff) [reply src/record.jl]: Alright, removed it.

**Comment by davidanthoff** [comment]
@shashi Apart from the one comment you made, are you on board with this? How do you want the `StringArray` situation to be handled?

**Comment by davidanthoff** [comment]
@joshday also pinging you on this. Are you the main point person for JuliaDB stuff these days? Would be good to get feedback from the JuliaDB side of things how you want to handle the `StringArray` situation here. Short summary: currently TextParse generally doesn't handle escaped strings properly. This PR here fixes that (I think) for the `Vector{String}` case, but not for `StringArray` columns.

In my mind we have three choices of how to handle this right now: 1) fix the bug only for `Vector{String}`, and leave the old behavior for `StringArray` around, 2) throw a bug if an escaped string comes up with `StringArray`, 3) someone from the JuliaDB side fixes this for `StringArray` as well, and everything is great :) Option 3 would obviously be best, but if there are constraints that make that tricky, it would be good to know whether you prefer 1) or 2) (I'm leaning towards 1), but I think you guys should make that call).

**Comment by joshday** [comment]
> Are you the main point person for JuliaDB stuff these days?

Yes, but half the time the first thing I do is bother @shashi!

I'd like to look into fixing this for StringArrays (👍 for option 3), and if this PR is good to go I say we merge it (start with option 1).

**Comment by davidanthoff** [comment]
Sounds good! I think if @shashi officially signs off on this PR we can merge it and then you can fix the `StringArray` case in another PR before we tag a new release.

The thing that made it appear slightly trickier to me for the `StringArray` case is how to do this without an extra temporary allocation. Essentially I think you want to grow the array buffer first (because you know by how much it needs to grow, and then loop over the characters in the source, skipping the ones that are escaped. But `StringArray` right now doesn't seem to provide an API for that kind of thing...

**Comment by davidanthoff** [comment]
Also, someone should just clone @shashi, that would be all around a good thing :)

**Comment by shashi** [comment]
Oh no! Sorry for the hold up here! Been super busy with coursework! :(

This change looks good. I like the separation of concern to `_substring`, but distrust the increase in the number of arguments. But it's OK.

> I generally have changed how the case of `Vector{String}` is handled: in that case this PR is no longer using `StrRange` at all, but is allocating the `String` in the `tryparsenext` method itself. I didn't see a benefit of going through `StrRange`, and it cuts down on the places that need to handle the escaping stuff.

This is a good change, `StrRange` was introduced in Julia 0.6 when we still boxed immutable structs with Strings in them. Ideally we should try to remove it entirely because it's also quite redundant with WeakRefString.

> Or, alternatively, but clearly not ideal, we could also for now just fix the bug for the `Vector{String}` case and then later try to fix it for `StringArray` as well.

This is OK. I couldn't figure out how a user can say "Don't try to un-escape quotes when parsing with the StringArray type", do they just get an error in this case? We should probably not throw here -- otherwise it's really evil towards those who are currently using this to parse strings with escaped quotes!

File: src/field.jl [hunk 5]
```diff
@@ -358,14 +364,41 @@ function tryparsenext(s::StringToken{T}, str, i, len, opts) where {T}
...
+            cur_i = nextind(str, cur_i)
+        end
+        return String(take!(buf))
+    else
+        return unsafe_string(pointer(str, i), j-i+1)
+    end
 end
 
-@inline function _substring(::Type{T}, str, i, j) where {T<:SubString}
+@inline function _substring(::Type{T}, str, i, j, escapecount, escapechar, quotechar, includequotes) where {T<:SubString}
```
Comment (shashi) [inline src/field.jl]: why not just take opts as the last argument?

File: test/runtests.jl [hunk 6]
```diff
@@ -302,12 +302,12 @@ import TextParse: quotedsplit
...
     @test quotedsplit("\"x\", \"y\"", opts,true, 1, 8) == ["\"x\"", "\"y\""]
     str = """x\nx,"s,", "\\",x" """
-    @test quotedsplit(str, opts, false, 3, length(str)) == ["x", "s,", "\\\",x"]
+    @test quotedsplit(str, opts, false, 3, length(str)) == ["x", "s,", "\",x"]
     @test quotedsplit(",", opts, true, 1, 1) == ["", ""]
     @test quotedsplit(", ", opts, false, 1, 2) == ["", ""]
     str = "1, \"x \"\"y\"\" z\", 1"
     qopts = LocalOpts(',', false,'"', '"', false, false)
-    @test quotedsplit(str, qopts,true, 1, lastindex(str)) == ["1", "\"x \"\"y\"\" z\"", "1"]
+    @test quotedsplit(str, qopts,true, 1, lastindex(str)) == ["1", "\"x \"y\" z\"", "1"]
```
Comment (shashi) [inline test/runtests.jl]: we should continue to test the StringArray code path here.

Comment (shashi) [reply test/runtests.jl]: i.e. after we remove the error.

File: src/field.jl (hunk 5 above)
Comment (davidanthoff) [reply src/field.jl]: Yep, done!

**Comment by davidanthoff** [comment]
Some performance numbers here, just want to make sure I record them. I'm running this test on one file that has no escaped quote mark in any string column (this should take the fast path) and one file that has string columns with escaped quotes in it (this will be slower, but returns an incorrect value on `master`).

Here are the numbers for the file without escapes in it:
```
On master:
julia> @time csvread("uniform_string.csv", stringarraytype=Array);
  5.093425 seconds (20.01 M allocations: 1.105 GiB, 43.14% gc time)

With this PR:
julia> @time csvread("uniform_string.csv", stringarraytype=Array);
  5.014085 seconds (60.01 M allocations: 2.297 GiB, 52.21% gc time)
```
So that is all looking good.

The numbers for the file with escapes in it:
```
On master:
julia> @time csvread("uniform_escapedstring.csv", stringarraytype=Array);
  5.744557 seconds (20.01 M allocations: 1.403 GiB, 36.64% gc time)

With this PR:
julia> @time csvread("uniform_escapedstring.csv", stringarraytype=Array);
  9.589759 seconds (80.01 M allocations: 4.383 GiB, 54.45% gc time)
```
So here we have a slow down, but on the other hand, we fix the incorrect result from `master`.

Overall, I think this is ok in terms of performance, in particular because our baseline is sooo much faster than pretty much anything else out there. Plus, the fix pretty much _must_ slow us down.

**Comment by davidanthoff** [comment]
Alright, assuming tests pass, this would be ready for a merge from my side. There is a fair amount of new stuff in here relative to a few days ago :)

@shashi mentioned somewhere that we should also test the `StringArray` code paths. I agree, but on the other hand, as far as I can tell, those code paths are also not tested on `master` right now, so this PR is not really a regression on that front. So I would say that adding tests for the `StringArray` case could just be a new PR by someone that is independent from this one here.

This now is an implementation of option 1): it fixes the escape handling for the `stringarraytype=Array` case, but not the `stringarraytype=StringArray` case. It doesn't error in the latter case, it just preserves the old behavior for now.

I'm going to wait for one more nod from @shashi that he is ok with a merge here, and then I'm going to merge.

**Comment by shashi** [comment]
Looking good! Feel free to merge! `stringarraytype=StringArray` case can be handled by probably converting WeakRefString to string and invoking the same code as `Array` case if `escapecount > 0`.

**Comment by shashi** [comment]
We should look into the performance penalty a bit more before making this the default i.e. in StringArray.

How many string columns with quotes does the csv you're benchmarking have? And how many rows?

**Comment by davidanthoff** [comment]
We should probably restructure the test code in some way so that all the tests run for all the different source string types we support. Would be cool to also test with say a UTF16 string type, just to make sure that also works.

The numbers from above for the file with escaped strings are a 20 column, 1 million row file, where every string has an escaped quote character in it, so the fast path is never taken. I think that is probably the worst case upper bound, therefore.

There are _a lot_ of things we could do to make this more efficient, the current implementation is quite naive. I'll run my full benchmark suite over it tonight, but I am pretty positive that even with this naive implementation we might still be faster than any other serial CSV reader that I'm testing. But we'll see... In any case, I think there is a fair bit of room for improvement left. But my main objective right now is to just get the correct behavior.

**Comment by quinnj** [comment]
For StringArray, I actually had an idea the other day to have a `QuotedString` type that would implement the String interface and do the escaping lazily (basically on `show` and `string(x)`). I think performance-wise it could be a big win, because you just do the escaping lazily and avoid the upfront allocations that might not even be needed depending on what the user ends up doing later. I haven't really fleshed the idea out that far, but thought I'd mention it in case someone else wants to explore the idea a little more.
